[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flowright"
version = "0.1.0"
description = "FloWright: It Takes Workflows to Evolve Better Workflows"
license = {text = "Apache-2.0"}
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.10"
dynamic = ["dependencies"]

[project.optional-dependencies]
test = ["pytest", "pytest-asyncio"]
gpu = ["liger-kernel", "flash-attn"]
vllm = ["vllm>=0.8.5"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*", "harness*", "flow*", "custom*", "assets*"]

[tool.setuptools.package-data]
"*" = ["version/*", "trainer/config/*.yaml", "trainer/config/*/*.yaml", "experimental/*/config/*.yaml"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "I", "G"]
ignore = ["F405", "F403", "E731", "B007", "UP032", "G004", "UP045", "UP035"]
